config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

from config.settings.common import THE_SITE_NAME

urlpatterns = [
    path(
        '',
        TemplateView.as_view(
            template_name="home.html",
            extra_context={'the_site_name': THE_SITE_NAME},
        ),
        name='home',
    ),

    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    path('self-enquiry/', include('self_enquiry.urls')),
]

self_enquiry/urls.py
from django.urls import path

from self_enquiry.views import JournalListView, JournalDetailView
from self_enquiry.views import JournalCreateView, JournalUpdateView
from self_enquiry.views import JournalDeleteView, JournalConfirmDeleteView


app_name = "self_enquiry"
urlpatterns = [
    path(
        "create/",
        JournalCreateView.as_view(),
        name="create",
    ),
    path(
        "list/",
        JournalListView.as_view(),
        name="list",
    ),
    path(
        "<int:pk>/detail/",
        JournalDetailView.as_view(),
        name="detail",
    ),
    path(
        "<int:pk>/update/",
        JournalUpdateView.as_view(),
        name="update",
    ),
    path(
        "<int:pk>/delete/",
        JournalDeleteView.as_view(),
        name="delete",
    ),
    path(
        "<int:pk>/confirm-delete/",
        JournalConfirmDeleteView.as_view(),
        name="confirm-delete",
    ),
]

self_enquiry/models.py
from django.db import models
from django.urls import reverse

from config.settings.common import AUTH_USER_MODEL
from base.models import CreatedUpdatedBase


class Journal(CreatedUpdatedBase):
    """
    Model for a User's Journal.

    Attributes:
        author (ForeignKey): The user that owns the journal.
        title (CharField): The title of the journal.
        content (TextField): The content of the journal.
        created (DateTimeField): The date and time the journal was created.
    """

    author = models.ForeignKey(
        AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="journals",
    )
    title = models.CharField(
        verbose_name="Journal Title",
        help_text="Optional - 100 characters or fewer",
        max_length=100,
        null=True,
        blank=True,
    )
    content = models.TextField(
        verbose_name="Journal Content",
        help_text="Required",
    )

    def __str__(self):
        return (
            self.author.username
            + " : "
            + str(self.pk)
            + (
                # If title is not `None`, then add it to the string.
                (" - " + self.title[:24])
                if self.title
                else ""
            )
        )

    def get_absolute_url(self):
        """
        This function returns the absolute URL for a journal. It is used for the view which needs to be redirected to after a journal is created or updated.
        """
        return reverse("self_enquiry:detail", args=[str(self.pk)])

    def display_content(self):
        """
        This function returns a truncated version of the journal's content. This can be used in the admin panel and other places where the full content is not needed.
        """
        return self.content[:50] + ("..." if len(self.content) > 50 else "")


class GrowthOpportunity(CreatedUpdatedBase):
    """
    The `GrowthOpportunity` model represents a growth opportunity or
    question that a user is interested in pursuing.

    Attributes:
        author (ForeignKey): The user that owns the growth opportunity.
        question (TextField): The question or growth opportunity.
        created (DateTimeField): The date and time the growth opportunity was created.
        updated (DateTimeField): The date and time the growth opportunity was last updated.
    """

    author = models.ForeignKey(
        AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="growth_opportunities",
    )
    question = models.TextField(
        verbose_name="Question",
        help_text="Required",
    )
    def __str__(self):
        return self.question[:24] + ("..." if len(self.question) > 24 else "")

    class Meta:
        verbose_name = "Growth Opportunity"
        verbose_name_plural = "Growth Opportunities"

self_enquiry/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView, View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse
from django.urls.base import reverse_lazy

from config.settings.common import THE_SITE_NAME
from .models import Journal


JOURNAL_LIST_PAGE_TITLE = "Journals"
JOURNAL_CREATE_PAGE_TITLE = "Create a Journal"
JOURNAL_CREATE_FORM_BUTTON_TEXT = "Create your Journal!"
JOURNAL_UPDATE_PAGE_TITLE = "Update a Journal"
JOURNAL_UPDATE_FORM_BUTTON_TEXT = "Update your Journal!"
JOURNAL_DELETE_PAGE_TITLE = "Delete a Journal"
JOURNAL_DELETE_FORM_BUTTON_TEXT = "Delete your Journal!"
JOURNAL_DETAIL_PAGE_TITLE = "Journal Detail"


class JournalCreateView(LoginRequiredMixin, CreateView):
    """
    Create view for a new `self_enquiry.Journal`.
    """

    model = Journal
    template_name = "self_enquiry/journal_form.html"
    fields = ["title", "content"]
    extra_context = {
        "the_site_name": THE_SITE_NAME,
        "page_title": JOURNAL_CREATE_PAGE_TITLE,
        "form_button_text": JOURNAL_CREATE_FORM_BUTTON_TEXT,
    }
    success_url = reverse_lazy("self_enquiry:list")

    def form_valid(self, form):
        """
        Override the default form_valid method to add the current user to the `author` field.
        """
        form.instance.author = self.request.user
        return super().form_valid(form)


class JournalListView(LoginRequiredMixin, ListView):
    """
    List view a user's `self_enquiry.Journal`s.
    """

    model = Journal
    ordering = ["-created"]
    paginate_by = 10
    extra_context = {
        "the_site_name": THE_SITE_NAME,
        "page_title": JOURNAL_LIST_PAGE_TITLE,
    }

    def get_queryset(self):
        """
        Override the default queryset to only return journals that belong to the current user.
        """
        return super().get_queryset().filter(author=self.request.user)


class JournalDetailView(UserPassesTestMixin, DetailView):
    """
    Detail view for a single `self_enquiry.Journal`.
    """

    model = Journal
    extra_context = {
        "the_site_name": THE_SITE_NAME,
        "page_title": JOURNAL_DETAIL_PAGE_TITLE,
    }

    def test_func(self):
        """
        Override the default test_func method to only allow the author of the journal to view it.
        """
        journal = self.get_object()
        return self.request.user == journal.author


class JournalUpdateView(UserPassesTestMixin, UpdateView):
    """
    Update view for a single `self_enquiry.Journal`.
    """

    model = Journal
    template_name = "self_enquiry/journal_form.html"
    fields = ["title", "content"]
    extra_context = {
        "the_site_name": THE_SITE_NAME,
        "page_title": JOURNAL_UPDATE_PAGE_TITLE,
        "form_button_text": JOURNAL_UPDATE_FORM_BUTTON_TEXT,
    }
    object = None

    def form_valid(self, form):
        """
        Override the default form_valid method to add the current user to the `author` field.
        """
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        """
        Override the default test_func method to only allow the author of the journal to view it.
        """
        journal = self.get_object()
        return self.request.user == journal.author


class JournalConfirmDeleteView(LoginRequiredMixin, View):
    """
    Confirm delete view for a single `self_enquiry.Journal`.
    """

    template_name = "self_enquiry/journal_confirm_delete.html"

    def get(self, request, *args, **kwargs):
        # Assuming you pass the journal ID in the URL
        journal_id = kwargs["pk"]
        journal = get_object_or_404(Journal, pk=journal_id)
        context = {
            "journal": journal,
            "the_site_name": THE_SITE_NAME,
            "page_title": JOURNAL_DELETE_PAGE_TITLE,
        }
        return render(request, self.template_name, context)


class JournalDeleteView(LoginRequiredMixin, DeleteView):
    model = Journal
    # Template for the confirmation page
    template_name = "self_enquiry/journal_confirm_delete.html"

    # TODO: Add a `message` that the Journal was deleted successfully.

    def get_success_url(self):
        return reverse(
            "self_enquiry:list",
        )

self_enquiry/templates/self_enquiry/journal_confirm_delete.html
{% extends "base.html" %}

{% block title %}
    {{ the_site_name }}
    -
    {{ page_title }}
{% endblock title %}

{% block content %}
    <h1>Confirm Delete</h1>
    <p>Are you sure you want to delete journal: {{ journal.title }}?</p>

    <form method="post" action="{% url 'self_enquiry:delete' journal.id %}">
        {% csrf_token %}
        <button type="submit">Confirm Delete</button>
        {% comment %} Allow cancellation of the deletion {% endcomment %}
        <a href="{% url 'self_enquiry:detail' journal.id %}">Cancel</a>
    </form>
{% endblock content %}

self_enquiry/templates/self_enquiry/journal_detail.html
{% extends "base.html" %}

{% block title %}{{ the_site_name }} - {{ page_title }}{% endblock title %}

{% block content %}
<h2>{{ journal.title }} - {{ journal.created }}</h2>
{{ journal.content | linebreaks }}
<a href="{% url 'self_enquiry:update' journal.id %}">Edit Journal</a>
<a href="{% url 'self_enquiry:confirm-delete' journal.id %}">Delete Journal</a>
{% endblock content %}

self_enquiry/templates/self_enquiry/journal_form.html
{% extends "base.html" %}

{% block title %}
    {{ the_site_name }}
    -
    {{ page_title }}
{% endblock title %}

{% block content %}
<h1>{{ page_title }}</h1>
<form method='post'>
    {% csrf_token %}
        {{ form.as_p }}
    <button type="submit" >{{ form_button_text }}</button>
    {% if request.resolver_match.view_name == "self_enquiry:update" %}
    {% comment %} button to cancel the update {% endcomment %}
    <a href="{% url 'self_enquiry:detail' pk=journal.pk %}">Cancel</a>
    {% elif request.resolver_match.view_name == "self_enquiry:create" %}
    {% comment %} button to cancel the add {% endcomment %}
    <a href="{% url 'self_enquiry:list' %}">Cancel</a>
    {% endif %}
</form>
{% endblock content %}

self_enquiry/templates/self_enquiry/journal_list.html
{% extends "base.html" %}

{% block title %}{{ the_site_name }} - {{ page_title }}{% endblock title %}

{% block content %}
    <h1>{{ page_title }}</h1>

    <a href="{% url 'self_enquiry:create' %}">Create Journal</a>

    {% if user.registration_accepted %}
        {% for journal in journal_list %}
            <hr>
            <h2><a href="{% url 'self_enquiry:detail' journal.id %}">{{ journal.title }}</a></h2>
            <h3>{{ journal.created }}</h3>
            {{ journal.content | linebreaks }}
        {% endfor %}
    {% endif %}

{% endblock content %}